# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ohg < Formula
  desc "Local-first carrier verification and freight risk review CLI."
  homepage "https://github.com/johnmonarch/OpenCarrier"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnmonarch/OpenCarrier/releases/download/v0.1.0/ohg_0.1.0_darwin_amd64.tar.gz"
      sha256 "f5e97ff116a05e1a4f11d23cda1dfa005830c53353d28da55271805c0134f276"

      define_method(:install) do
        bin.install "ohg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnmonarch/OpenCarrier/releases/download/v0.1.0/ohg_0.1.0_darwin_arm64.tar.gz"
      sha256 "7173bbf25da7d53828dee3cd696720f5f9962e33fab08feee2f7965b10d56302"

      define_method(:install) do
        bin.install "ohg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnmonarch/OpenCarrier/releases/download/v0.1.0/ohg_0.1.0_linux_amd64.tar.gz"
      sha256 "725e21bf2fc81b7192b837ec0482aa33dd5a0d4b9e243d18a12406f943ca74b5"
      define_method(:install) do
        bin.install "ohg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnmonarch/OpenCarrier/releases/download/v0.1.0/ohg_0.1.0_linux_arm64.tar.gz"
      sha256 "dad8f28fa2cac746aaa78de94598433db25b55199c66e15e89105603f53f90da"
      define_method(:install) do
        bin.install "ohg"
      end
    end
  end

  test do
    system "#{bin}/ohg", "--version"
  end
end
