# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ohg < Formula
  desc "Local-first carrier verification and freight risk review CLI."
  homepage "https://github.com/johnmonarch/OpenHaul"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/johnmonarch/OpenHaul/releases/download/v0.2.1/ohg_0.2.1_darwin_amd64.tar.gz"
      sha256 "f34d4fdc0c0a4beb92000dbe069779d1c3ca0c028ec6a453e4763fb1e4a4653b"

      define_method(:install) do
        bin.install "ohg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/johnmonarch/OpenHaul/releases/download/v0.2.1/ohg_0.2.1_darwin_arm64.tar.gz"
      sha256 "065c3c528d9f9725a1644cd23c3a1618d960e346f95a97eb72753634f9c7804d"

      define_method(:install) do
        bin.install "ohg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnmonarch/OpenHaul/releases/download/v0.2.1/ohg_0.2.1_linux_amd64.tar.gz"
      sha256 "8e770e8be89eea033fb8745a98c7b9d6825058f91e66359e6003e6aec439b9c3"
      define_method(:install) do
        bin.install "ohg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/johnmonarch/OpenHaul/releases/download/v0.2.1/ohg_0.2.1_linux_arm64.tar.gz"
      sha256 "a9317859d98d0dfc06182b90c17a1dd29cbaa5fc34df3a72504943a84f5290eb"
      define_method(:install) do
        bin.install "ohg"
      end
    end
  end

  test do
    system "#{bin}/ohg", "--version"
  end
end
